import React from 'react';
import { render, screen } from '@testing-library/react';
import {
  aggregateLeadsByCampaign,
  aggregateLeadsBySource,
  groupCampaignsForChart,
  WaTrackerSummaryCharts,
} from '@/components/dashboard/WaTrackerSummaryCharts';

describe('WA Tracker summary charts', () => {
  const groups = [
    { source: 'Google', campaign: 'Search', leads: 8 },
    { source: 'Organic', campaign: 'Organic', leads: 12 },
    { source: 'Google', campaign: 'PMax', leads: 5 },
  ];

  it('aggregates and sorts lead totals by source and campaign', () => {
    expect(aggregateLeadsBySource(groups)).toEqual([
      { name: 'Google', leads: 13 },
      { name: 'Organic', leads: 12 },
    ]);
    expect(aggregateLeadsByCampaign(groups)).toEqual([
      { name: 'Organic', leads: 12 },
      { name: 'Search', leads: 8 },
      { name: 'PMax', leads: 5 },
    ]);
  });

  it('groups smaller campaigns without changing the lead total', () => {
    const campaigns = Array.from({ length: 10 }, (_, index) => ({
      name: `Campaign ${index + 1}`,
      leads: 10 - index,
    }));

    const result = groupCampaignsForChart(campaigns, 8);

    expect(result).toHaveLength(8);
    expect(result.at(-1)).toEqual({ name: 'Other campaigns (3)', leads: 6 });
    expect(result.reduce((total, campaign) => total + campaign.leads, 0)).toBe(55);
  });

  it('renders accessible source and campaign comparisons', () => {
    render(
      <WaTrackerSummaryCharts
        groups={groups}
        dailyLeads={[
          { date: '2026-06-11', leads: 2 },
          { date: '2026-06-12', leads: 0 },
          { date: '2026-06-13', leads: 3 },
        ]}
        average={5 / 3}
      />,
    );

    expect(screen.getByText('Leads by Source')).toBeInTheDocument();
    expect(screen.getByText('Leads Generated by Campaign')).toBeInTheDocument();
    expect(screen.getByText('Total Leads per Day')).toBeInTheDocument();
    expect(screen.getByRole('img', { name: /Google: 13, Organic: 12/i })).toBeInTheDocument();
    expect(screen.getByRole('img', { name: /Daily average 1,7/i })).toBeInTheDocument();
    expect(screen.getByRole('list', { name: 'Campaign lead ranking' })).toBeInTheDocument();
    expect(screen.getByText('Avg 1,7')).toBeInTheDocument();
    expect(screen.getAllByText('25')).toHaveLength(2);
  });

  it('shows empty states when the selected period has no leads', () => {
    render(<WaTrackerSummaryCharts groups={[]} />);

    expect(screen.getAllByText('No lead data for the selected period.')).toHaveLength(3);
  });
});
